package com.aschiesch.dspiel.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val gBlack = Color(0xFF000000)
val gRed = Color(0xFFDD0000)
val gYellow = Color(0xFFFFCE00)

val primaryLight = Color(0xFF006879)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFAAEDFF)
val onPrimaryContainerLight = Color(0xFF001F26)
val secondaryLight = Color(0xFF3C6090)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD4E3FF)
val onSecondaryContainerLight = Color(0xFF001C3A)
val tertiaryLight = Color(0xFF625690)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE7DEFF)
val onTertiaryContainerLight = Color(0xFF1E1048)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFC)
val onBackgroundLight = Color(0xFF171C1E)
val surfaceLight = Color(0xFFF5FAFC)
val onSurfaceLight = Color(0xFF171C1E)
val surfaceVariantLight = Color(0xFFDBE4E7)
val onSurfaceVariantLight = Color(0xFF3F484B)
val outlineLight = Color(0xFF70797B)
val outlineVariantLight = Color(0xFFBFC8CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3133)
val inverseOnSurfaceLight = Color(0xFFECF2F4)
val inversePrimaryLight = Color(0xFF84D2E6)
val surfaceDimLight = Color(0xFFD5DBDD)
val surfaceBrightLight = Color(0xFFF5FAFC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF4F6)
val surfaceContainerLight = Color(0xFFE9EFF1)
val surfaceContainerHighLight = Color(0xFFE4E9EB)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryLightMediumContrast = Color(0xFF004A57)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF297F91)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF1D4472)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF5376A7)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF463A72)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF796CA8)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FAFC)
val onBackgroundLightMediumContrast = Color(0xFF171C1E)
val surfaceLightMediumContrast = Color(0xFFF5FAFC)
val onSurfaceLightMediumContrast = Color(0xFF171C1E)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E7)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B4447)
val outlineLightMediumContrast = Color(0xFF586163)
val outlineVariantLightMediumContrast = Color(0xFF737C7F)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C3133)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F4)
val inversePrimaryLightMediumContrast = Color(0xFF84D2E6)
val surfaceDimLightMediumContrast = Color(0xFFD5DBDD)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF4F6)
val surfaceContainerLightMediumContrast = Color(0xFFE9EFF1)
val surfaceContainerHighLightMediumContrast = Color(0xFFE4E9EB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDEE3E5)

val primaryLightHighContrast = Color(0xFF00262E)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004A57)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF002246)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF1D4472)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF25184F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF463A72)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FAFC)
val onBackgroundLightHighContrast = Color(0xFF171C1E)
val surfaceLightHighContrast = Color(0xFFF5FAFC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE4E7)
val onSurfaceVariantLightHighContrast = Color(0xFF1D2528)
val outlineLightHighContrast = Color(0xFF3B4447)
val outlineVariantLightHighContrast = Color(0xFF3B4447)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C3133)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC9F3FF)
val surfaceDimLightHighContrast = Color(0xFFD5DBDD)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF4F6)
val surfaceContainerLightHighContrast = Color(0xFFE9EFF1)
val surfaceContainerHighLightHighContrast = Color(0xFFE4E9EB)
val surfaceContainerHighestLightHighContrast = Color(0xFFDEE3E5)

val primaryDark = Color(0xFF84D2E6)
val onPrimaryDark = Color(0xFF003640)
val primaryContainerDark = Color(0xFF004E5C)
val onPrimaryContainerDark = Color(0xFFAAEDFF)
val secondaryDark = Color(0xFFA6C8FF)
val onSecondaryDark = Color(0xFF00315E)
val secondaryContainerDark = Color(0xFF224876)
val onSecondaryContainerDark = Color(0xFFD4E3FF)
val tertiaryDark = Color(0xFFCCBDFF)
val onTertiaryDark = Color(0xFF33275E)
val tertiaryContainerDark = Color(0xFF4A3E76)
val onTertiaryContainerDark = Color(0xFFE7DEFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1416)
val onBackgroundDark = Color(0xFFDEE3E5)
val surfaceDark = Color(0xFF0F1416)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF3F484B)
val onSurfaceVariantDark = Color(0xFFBFC8CB)
val outlineDark = Color(0xFF899295)
val outlineVariantDark = Color(0xFF3F484B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2C3133)
val inversePrimaryDark = Color(0xFF006879)
val surfaceDimDark = Color(0xFF0F1416)
val surfaceBrightDark = Color(0xFF343A3C)
val surfaceContainerLowestDark = Color(0xFF090F11)
val surfaceContainerLowDark = Color(0xFF171C1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2D)
val surfaceContainerHighestDark = Color(0xFF303637)

val primaryDarkMediumContrast = Color(0xFF88D6EA)
val onPrimaryDarkMediumContrast = Color(0xFF00191F)
val primaryContainerDarkMediumContrast = Color(0xFF4B9BAE)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFADCCFF)
val onSecondaryDarkMediumContrast = Color(0xFF001631)
val secondaryContainerDarkMediumContrast = Color(0xFF7092C6)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD0C2FF)
val onTertiaryDarkMediumContrast = Color(0xFF190A43)
val tertiaryContainerDarkMediumContrast = Color(0xFF9588C6)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1416)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E5)
val surfaceDarkMediumContrast = Color(0xFF0F1416)
val onSurfaceDarkMediumContrast = Color(0xFFF6FCFE)
val surfaceVariantDarkMediumContrast = Color(0xFF3F484B)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC3CCCF)
val outlineDarkMediumContrast = Color(0xFF9BA4A7)
val outlineVariantDarkMediumContrast = Color(0xFF7C8587)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2D)
val inversePrimaryDarkMediumContrast = Color(0xFF004F5D)
val surfaceDimDarkMediumContrast = Color(0xFF0F1416)
val surfaceBrightDarkMediumContrast = Color(0xFF343A3C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F11)
val surfaceContainerLowDarkMediumContrast = Color(0xFF171C1E)
val surfaceContainerDarkMediumContrast = Color(0xFF1B2122)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252B2D)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303637)

val primaryDarkHighContrast = Color(0xFFF4FCFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF88D6EA)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFBFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFADCCFF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFEF9FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD0C2FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0F1416)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E5)
val surfaceDarkHighContrast = Color(0xFF0F1416)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F484B)
val onSurfaceVariantDarkHighContrast = Color(0xFFF4FCFF)
val outlineDarkHighContrast = Color(0xFFC3CCCF)
val outlineVariantDarkHighContrast = Color(0xFFC3CCCF)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002F38)
val surfaceDimDarkHighContrast = Color(0xFF0F1416)
val surfaceBrightDarkHighContrast = Color(0xFF343A3C)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F11)
val surfaceContainerLowDarkHighContrast = Color(0xFF171C1E)
val surfaceContainerDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B2D)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303637)















